version: '2'
services:
  log:
    image: vmware/harbor-log:dev
    container_name: harbor-log 
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/
    ports:
      - 1514:514
    networks:
      - harbor
  registry:
    image: registry:2.5.1
    container_name: registry
    restart: always
    volumes:
      - /data/harbor/registry:/storage
      - /data/harbor/common/config/registry/:/etc/registry/
    networks:
      - harbor
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  mysql:
    image: vmware/harbor-db:dev
    container_name: harbor-db
    restart: always
    volumes:
      - /data/harbor/database:/var/lib/mysql
    networks:
      - harbor
    env_file:
      - /data/harbor/common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  adminserver:
    image: vmware/harbor-adminserver:dev
    container_name: harbor-adminserver
    env_file:
      - /data/harbor/common/config/adminserver/env
    restart: always
    volumes:
      - /data/harbor/config/:/etc/adminserver/
      - /data/harbor/secretkey:/etc/adminserver/key
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
  ui:
    image: vmware/harbor-ui:dev
    container_name: harbor-ui
    env_file:
      - /data/harbor/common/config/ui/env
    restart: always
    volumes:
      - /data/harbor/common/config/ui/app.conf:/etc/ui/app.conf
      - /data/harbor/common/config/ui/private_key.pem:/etc/ui/private_key.pem
      - /data/harbor:/harbor_storage
      - /data/harbor/secretkey:/etc/ui/key
    networks:
      - harbor
    depends_on:
      - log
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:dev
    container_name: harbor-jobservice
    env_file:
      - /data/harbor/common/config/jobservice/env
    restart: always
    volumes:
      - /data/harbor/job_logs:/var/log/jobs
      - /data/harbor/common/config/jobservice/app.conf:/etc/jobservice/app.conf
      - /data/harbor/secretkey:/etc/jobservice/key
    networks:
      - harbor
    depends_on:
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  proxy:
    image: nginx:1.11.5
    container_name: nginx
    restart: always
    volumes:
      - /data/harbor/common/config/nginx:/etc/nginx
    networks:
      - harbor
    ports:
      - <PORT>
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false
