---
clone:
  path: github.com/vmware/vic
  tags: true
build:
  image: golang:1.6.0
  pull: true
  environment:
    GOPATH: /drone
    SHELL: /bin/bash
    DOCKER_API_VERSION: "1.21"
  volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  commands:
    - wget -q https://get.docker.com/builds/Linux/x86_64/docker-latest
    - chmod +x docker-latest
    - mv docker-latest /usr/local/bin/docker
    - make all
    - make test
    - make integration-tests
