swagger: "2.0"
info:
  description: "Port Layer API"
  title: "Port Layer API"
  version: "v0.0.1"
produces:
- application/json
consumes:
- application/json
schemes:
- http
paths:
  /_ping:
    get:
      tags: ["misc"]
      operationId: Ping
      produces:
        - text/plain
      responses:
        '200':
          description: "OK"
          schema:
            type: string
  /storage:
    post:
      tags: ["storage"]
      operationId: CreateImageStore
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/ImageStore"
      responses:
        '201':
          description: "Created"
          schema:
            $ref: "#/definitions/StoreUrl"
        '409':
          description: "An image store with that name already exists."
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /storage/{store_name}:
    parameters:
      - name: store_name
        type: string
        in: path
        required: true
    get:
      tags: ["storage"]
      operationId: ListImages
      parameters:
        - name: id
          type: string
          in: query
          collectionFormat: multi
      responses:
        '200':
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Image"
        '404':
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
           $ref: "#/definitions/Error"
  /storage/{store_name}/writeImage:
    post:
      tags: ["storage"]
      operationId: WriteImage
      consumes:
        - application/octet-stream
      parameters:
        - name: image_file
          in: body
          schema:
            type: string
            format: binary
        - name: store_name
          type: string
          in: path
          required: true
        - name: image_id
          type: string
          in: query
          required: true
        - name: parent_id
          type: string
          in: query
          required: true
      responses:
        '201':
          description: "Created"
          schema:
            $ref: "#/definitions/Image"
        default:
          description: "error"
          schema:
           $ref: "#/definitions/Error"
  /storage/{store_name}/info/{id}:
    parameters:
      - name: store_name
        type: string
        in: path
        required: true
      - name: id
        type: string
        in: path
        required: true
    get:
      tags: ["storage"]
      operationId: GetImage
      responses:
        '404':
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        '200':
          description: "OK"
          schema:
            $ref: "#/definitions/Image"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /storage/{store_name}/tar/{id}:
    parameters:
      - name: store_name
        type: string
        in: path
        required: true
      - name: id
        type: string
        in: path
        required: true
    get:
      tags: ["storage"]
      operationId: GetImageTar
      responses:
        '404':
          description: "Not found"
        '200':
          description: "OK"
          schema:
            type: string
            format: binary
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  StoreUrl:
    type: object
    required:
      - url
    properties:
      code:
        type: integer
        format: int64
      url:
        type: string
  ImageStore:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  Image:
    type: object
    required:
      - ID
      - Store
    properties:
      ID:
        type: string
      SelfLink:
        type: string
      Parent:
        type: string
      Store:
        type: string
