swagger: "2.0"
info:
  description: "Port Layer API"
  title: "Port Layer API"
  version: "v0.0.1"
produces:
- application/json
consumes:
- application/json
schemes:
- http
paths:
  /storage:
    post:
      tags: ["storage"]
      operationId: CreateImageStore
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/ImageStore"
      responses:
        '201':
          description: "Created"
          schema:
            $ref: "#/definitions/StoreUrl"
        '400':
          description: "An image store with that name already exists."
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /storage/{store_name}:
    parameters:
      - name: store_name
        type: string
        in: path
        required: true
    get:
      tags: ["storage"]
      operationId: ListImages
      parameters:
        - name: id
          type: string
          in: query
          collectionFormat: multi
      responses:
        '200':
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Image"
        '404':
          description: "Not found"
        default:
          description: "error"
          schema:
           $ref: "#/definitions/Error"
    post:
      tags: ["storage"]
      operationId: WriteImage
      parameters:
        - name: id
          in: body
          schema:
            $ref: "#/definitions/ImageWithBody"
      consumes:
        - application/x-tar
        - application/x-gzip
      responses:
        '201':
          description: "Created"
          schema:
            $ref: "#/definitions/Image"
        default:
          description: "error"
          schema:
           $ref: "#/definitions/Error"
  /storage/{store_name}/info/{id}:
    parameters:
      - name: store_name
        type: string
        in: path
        required: true
      - name: id
        type: string
        in: path
        required: true
    get:
      tags: ["storage"]
      operationId: GetImage
      responses:
        '404':
          description: "Not found"
        '200':
          description: "OK"
          schema:
            $ref: "#/definitions/Image"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /storage/{store_name}/tar/{id}:
    parameters:
      - name: store_name
        type: string
        in: path
        required: true
      - name: id
        type: string
        in: path
        required: true
    get:
      tags: ["storage"]
      operationId: GetImageTar
      produces:
        - application/gzip
      responses:
        '404':
          description: "Not found"
        '200':
          description: "OK"
          schema:
            $ref: "#/definitions/ImageTar"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  StoreUrl:
    type: object
    required:
      - url
    properties:
      code:
        type: integer
        format: int64
      url:
        type: string
  ImageStore:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  Image:
    type: object
    required:
      - ID
      - Store
    properties:
      ID:
        type: string
      SelfLink:
        type: string
      Parent:
        type: string
      Store:
        type: string
  ImageWithBody:
    type: object
    properties:
      Image:
        $ref: "#/definitions/Image"
      Data:
        type: object
  ImageTar:
    type: string
    format: base64
